# Generated by Django 5.1.6 on 2025-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myapp_join_date_myapp_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_driven', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], max_length=10)),
                ('seller_type', models.CharField(choices=[('Dealer', 'Dealer'), ('Individual', 'Individual')], max_length=10)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('owner', models.CharField(choices=[('First Owner', 'First Owner'), ('Second Owner', 'Second Owner'), ('Third Owner', 'Third Owner'), ('Fourth & Above Owner', 'Fourth & Above Owner'), ('Test Drive Car', 'Test Drive Car')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Myapp',
        ),
    ]
